"""
unseen_review_loader.py
───────────────────────
Loads the held-out test split used during model evaluation and reconstructs
the original review text by cross-referencing the saved test labels (y_test)
with the processed CSV via index alignment.

These reviews were NOT seen by the model during training (stratified 80/20 split).
The sentiment shown is generated by our SAVED ML model — not from training labels.
"""

import os
import joblib
import pandas as pd
import streamlit as st

MODELS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "backend", "models"
)
DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "backend", "data", "processed", "amazon_all_beauty_reviews.csv"
)


@st.cache_data(show_spinner=False)
def load_unseen_reviews(n_samples: int = 200, model_name: str = "balanced_logistic_regression") -> pd.DataFrame:
    """
    Returns a DataFrame of genuinely held-out reviews with ML-predicted sentiment.

    Strategy:
      - Load the full processed CSV
      - Re-apply the SAME deterministic train/test split (random_state=42, stratify=y)
        to identify which rows are the test partition
      - Load the saved ML model and TF-IDF vectorizer
      - Run inference on the test rows (they were not seen during training)
      - Return n_samples rows with original metadata + ML sentiment

    The column 'label_sentiment' holds the original label (from rating rule).
    The column 'sentiment' holds the ML model prediction (what we display).
    """
    try:
        from sklearn.model_selection import train_test_split

        # Load CSV
        df_full = pd.read_csv(
            DATA_PATH,
            dtype={
                "review_id": str, "text": str, "title": str,
                "rating": float, "product": str, "category": str,
                "price": str, "date": str, "helpful_votes": int,
                "verified_purchase": bool, "sentiment": str,
                "clean_text": str, "source": str,
            }
        )
        df_full["text"]       = df_full["text"].fillna("")
        df_full["title"]      = df_full["title"].fillna("")
        df_full["rating"]     = pd.to_numeric(df_full["rating"], errors="coerce").fillna(5.0)
        df_full["helpful_votes"] = pd.to_numeric(df_full["helpful_votes"], errors="coerce").fillna(0).astype(int)
        df_full["verified_purchase"] = df_full["verified_purchase"].fillna(False).astype(bool)
        df_full["clean_text"] = df_full["clean_text"].fillna("")
        df_full["sentiment"]  = df_full["sentiment"].fillna("neutral").str.lower()

        # Replicate the EXACT split used during training
        _, idx_test = train_test_split(
            df_full.index,
            test_size=0.2,
            random_state=42,
            stratify=df_full["sentiment"]
        )

        df_test = df_full.loc[idx_test].copy().reset_index(drop=True)

        # Load vectorizer + model
        vec_path   = os.path.join(MODELS_DIR, "tfidf_vectorizer.joblib")
        model_path = os.path.join(MODELS_DIR, f"{model_name}.joblib")

        if not os.path.exists(vec_path) or not os.path.exists(model_path):
            return pd.DataFrame()

        vectorizer = joblib.load(vec_path)
        model      = joblib.load(model_path)

        # Sample for speed (stratified to preserve class distribution)
        sample_size = min(n_samples, len(df_test))
        sampled_dfs = []
        for _, group in df_test.groupby("sentiment"):
            n_group = max(1, int(round(sample_size * len(group) / len(df_test))))
            sampled_dfs.append(group.sample(min(len(group), n_group), random_state=42))
        df_sample = pd.concat(sampled_dfs, ignore_index=True).sample(frac=1.0, random_state=42).head(sample_size).reset_index(drop=True)

        # Run ML inference on held-out text (model never saw this during training)
        X = vectorizer.transform(df_sample["clean_text"])
        predictions = model.predict(X)

        # Confidence for LR models; None for LinearSVC
        confidence_vals = None
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(X)
            confidence_vals = proba.max(axis=1)

        # Build result DataFrame
        df_sample["label_sentiment"] = df_sample["sentiment"]   # original label (from rating rule)
        df_sample["sentiment"]       = predictions               # ML model output ← what we DISPLAY
        df_sample["model_name"]      = model_name
        df_sample["confidence"]      = confidence_vals.tolist() if confidence_vals is not None else [None] * len(df_sample)
        df_sample["source"]          = "amazon_reviews_2023_test_split"

        # Mismatch: model prediction vs original star rating
        df_sample["is_mismatch"] = (
            ((df_sample["rating"] >= 4.0) & (df_sample["sentiment"] == "negative")) |
            ((df_sample["rating"] <= 2.0) & (df_sample["sentiment"] == "positive"))
        )

        return df_sample[[
            "review_id", "text", "title", "rating", "product",
            "date", "helpful_votes", "verified_purchase",
            "label_sentiment", "sentiment", "confidence",
            "model_name", "source", "is_mismatch", "clean_text"
        ]]

    except Exception as e:
        # Never crash the dashboard
        st.warning(f"Could not load unseen review analysis: {e}")
        return pd.DataFrame()
